from snakemake.utils import min_version

# Based on:
# https://github.com/rberrens/SPOCD1-piRNA_directed_DNA_met/tree/master/piRNA_analysis


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"


# Set minimum snakemake version
min_version("8.25.5")


# Define Docker container
containerized: "docker://niekwit/smallrna-seq:v0.1"


GENOME = config["genome"]
SAMPLES = samples()
NCRNA_URL = ensembl_ncrna_url(config)

# Only use a leader sample when the TEsmall genome database does not yet exist
_tesmall_genome_db = os.path.join(config["tesmall"]["dbfolder"], "genomes", GENOME)
LEADER_SAMPLE = SAMPLES[0] if not os.path.isdir(_tesmall_genome_db) else None
EXT = ["1.ebwt", "2.ebwt", "3.ebwt", "4.ebwt", "rev.1.ebwt", "rev.2.ebwt"]
COMPARISONS = comparisons(config)
TE = te(config)
MIRBASE_GENOME = mirbase_genome(config)


include: "rules/length_distribution.smk"
include: "rules/te_small.smk"
include: "rules/pingpong.smk"
include: "rules/mirna_correction.smk"


onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# Target rule
# -----------------------------------------------------
TARGETS = [
    "results/plots/length_distribution.pdf",
    "results/plots/pingpong.pdf",
    "results/plots/pingpong.csv",
    expand(
        "results/plots/pirna_sequence_bias/{te}/{comparison}_logo.pdf",
        te=TE,
        comparison=COMPARISONS,
    ),
    expand(
        "results/plots/pirna_sequence_bias/{te}/{comparison}_bargraph.pdf",
        te=TE,
        comparison=COMPARISONS,
    ),
    expand(
        "results/plots/te_pos_coverage/{te}.pdf",
        te=TE,
    ),
]

if config["tesmall"]["run_tesmall"]:
    TARGETS.extend(
        [
            "results/plots/pca_plot.pdf",
            expand(
                "results/plots/{comparison}/volcano_plot.pdf", comparison=COMPARISONS
            ),
            expand("results/plots/{comparison}/results.csv", comparison=COMPARISONS),
            "results/plots/te_small/piechart.pdf",
            "results/plots/te_small/piechart.csv",
            "results/plots/te_small/bargraph.pdf",
            "results/plots/te_small/stacked_bar_te.pdf",
            "results/plots/te_small/stacked_bar_te.csv",
        ]
    )


rule all:
    input:
        TARGETS,
