# Based on:
# https://github.com/rberrens/SPOCD1-piRNA_directed_DNA_met/tree/master/piRNA_analysis

# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"


GENOME = config["genome"]
SAMPLES = samples()
LEADER_SAMPLE = SAMPLES[0]
EXT = ["1.ebwt", "2.ebwt", "3.ebwt", "4.ebwt", "rev.1.ebwt", "rev.2.ebwt"]
COMPARISONS = comparisons(config)

include: "rules/length_distribution.smk"
include: "rules/te_small.smk"
include: "rules/pingpong.smk"

onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# Target rule
# -----------------------------------------------------
rule all:
    input:
        "results/plots/length_distribution.pdf",
        "results/plots/pingpong.pdf",
        "results/plots/pingpong.csv",
        expand("results/plots/{comparison}/volcano_plot.pdf", comparison=COMPARISONS),
        expand("results/plots/{comparison}/results.csv", comparison=COMPARISONS),
        "results/plots/pca_plot.pdf",
